# .github/workflows/release-jar.yml
name: Build and Release Jar

on:
  push:
    tags:
      - 'v*'  # déclenché quand tu pushes un tag comme v1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build jar with dependencies
        run: mvn clean package

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*-jar-with-dependencies.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
